version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --ssl=0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutorial
    ports:
      - 3306:3306
    volumes:
      - ./mysql-init/:/docker-entrypoint-initdb.d